### ISSUE TITLE
Uninstalling a load command breaks another DYLIBs

### ISSUE THREAD

**Issue by anivaros** [alexzielenski/optool#13]
Hello! I'm trying to uninstall system lib:
```optool uninstall -p "/usr/lib/libsqlite3.dylib" -t "$TARGET_APP_PATH/$APP_BINARY"```
All looks like fine, see before and after ```otool -l``` output
[before.txt](https://github.com/alexzielenski/optool/files/1114607/before.txt)
[after.txt](https://github.com/alexzielenski/optool/files/1114608/after.txt)

But I'm getting an error in runtime about another lib:
> dyld: Symbol not found: _OBJC_CLASS_$_NSFileManager
>   Referenced from: /var/containers/Bundle/Application/7AFFEF62-62B4-4C44-BF78-4E20467B31AF/IPAPatch-DummyApp.app/Wrapping Test
>   Expected in: /usr/lib/libobjc.A.dylib
>  in /var/containers/Bundle/Application/7AFFEF62-62B4-4C44-BF78-4E20467B31AF/IPAPatch-DummyApp.app/Wrapping Test

Can I do something with that?

**Comment by alexzielenski** [comment]
A disclaimer is written in optool help that this is possible. The uninstall command is only really intended for removing optool-installed libraries.

**Comment by anivaros** [comment]
I understand that, but there is no possibility to fix that?
I need to inject my own version of sqlite3, but as I understand, I should remove default version of lib?

**Comment by alexzielenski** [comment]
I think `install_name_tool` would be useful for changing the path if I recall correctly but bound symbols may break. There's no recourse through optool for this use-case; however.
