### ISSUE TITLE
some bug for remove!

### ISSUE THREAD

**Issue by yjtortor** [alexzielenski/optool#3]
BOOL removeLoadEntryFromBinary(NSMutableData *binary, struct thin_header macho, NSString *payload) {
    // parse load commands to see if our load command is already there
    binary.currentOffset = macho.offset + macho.size;
    
    uint32_t num = 0;
    uint32_t cumulativeSize = 0;
    uint32_t removedOrdinal = -1;
...........
  if ([dylibname isEqualToString:payload] && removedOrdinal != -1) {
// if ([dylibname isEqualToString:payload] && removedOrdinal == -1) {   ???
............

removedOrdinal =-1, it will never remove the payload!!!

**Comment by alexzielenski** [comment]
You're right. I just fixed this. Sorry for taking so long, I had not noticed the GitHub issue.
