### ISSUE TITLE
can't clone your repository - it has a submodule to which I don't have access rights.

### ISSUE THREAD

**Issue by Motti-Shneor** [alexzielenski/optool#4]
Hi, I cloned the repo, but it didn't bring with it its submodule.

So, naturally, I tried 
git submodule init
git submodule update

and it failed because I didn't have "access rights" to the submodule.

Above this - you set your Xcode project "Base SDK" to 10.9, which no longer exists in recent Xcode releases (Xcode 6.4, Xcode 7.x)  

Can you please verify your repository is still usable?

**Comment by alexzielenski** [comment]
Seems like FSArgumentParser moved. I have updated .gitmodules and tested it. All should work now.

Thanks!

**Comment by Motti-Shneor** [comment]
tried again to clone your repo, using 

> git clone https://github.com/alexzielenski/optool.git

Right after cloning, the project is un-buildable (for lack of sources). 

and any subsequent “pull” with —recursive (to update submodules) still  yells about me not having the right private key to access the submodule. 

Maybe your FSArgumentParser submodule isn’t open-accessed at all?

I re-created the issue, sorry for the hassle - I just need the optool :)

Is it possible to have at least the “.zip” downloadable archive of your project to be internally complete and build able ?
