### ISSUE TITLE
Can't clone your repository - it has a submodule to which I don't have access rights.

### ISSUE THREAD

**Issue by Motti-Shneor** [alexzielenski/optool#5]
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree fetch origin 
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree pull origin master 
From https://github.com/alexzielenski/optool
 * branch            master     -> FETCH_HEAD
Already up-to-date.

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree submodule update --init --recursive 
Cloning into 'optool/FSArgumentParser'...
warning: templates not found /usr/local/git/share/git-core/templates
**Permission denied (publickey).
fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:NSError/ArgumentParser.git' into submodule path 'optool/FSArgumentParser' failed
Cloning into 'optool/FSArgumentParser'...
warning: templates not found /usr/local/git/share/git-core/templates
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:NSError/ArgumentParser.git' into submodule path 'optool/FSArgumentParser' failed
Cloning into 'optool/FSArgumentParser'...
warning: templates not found /usr/local/git/share/git-core/templates
**Permission denied (publickey).
fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:NSError/ArgumentParser.git' into submodule path 'optool/FSArgumentParser' failed
Cloning into 'optool/FSArgumentParser'...
warning: templates not found /usr/local/git/share/git-core/templates
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:NSError/ArgumentParser.git' into submodule path 'optool/FSArgumentParser' failed
Completed with errors, see above

**Comment by alexzielenski** [comment]
Looks like its still trying to pull from the old path at NSError/ArgumentParser instead of https://github.com/mysteriouspants/ArgumentParser.git.

Anyway, here is a build:
[optool.zip](https://github.com/alexzielenski/optool/files/91118/optool.zip)

**Comment by Motti-Shneor** [comment]
Thank you so much.

I think if a git submodule has moved, you can’t just commit the “change” of it, you’ll need to first remove it (as a submodule), then pull the new submodule and commit it as a new submodule.
